// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GRPC/TestProto.proto

package GRPCHandler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecievedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerID      string                 `protobuf:"bytes,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	AvailableSize string                 `protobuf:"bytes,2,opt,name=AvailableSize,proto3" json:"AvailableSize,omitempty"`
	ChunkList     string                 `protobuf:"bytes,3,opt,name=chunkList,proto3" json:"chunkList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecievedMessage) Reset() {
	*x = RecievedMessage{}
	mi := &file_GRPC_TestProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecievedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecievedMessage) ProtoMessage() {}

func (x *RecievedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_TestProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecievedMessage.ProtoReflect.Descriptor instead.
func (*RecievedMessage) Descriptor() ([]byte, []int) {
	return file_GRPC_TestProto_proto_rawDescGZIP(), []int{0}
}

func (x *RecievedMessage) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *RecievedMessage) GetAvailableSize() string {
	if x != nil {
		return x.AvailableSize
	}
	return ""
}

func (x *RecievedMessage) GetChunkList() string {
	if x != nil {
		return x.ChunkList
	}
	return ""
}

var File_GRPC_TestProto_proto protoreflect.FileDescriptor

const file_GRPC_TestProto_proto_rawDesc = "" +
	"\n" +
	"\x14GRPC/TestProto.proto\x12\vGRPCHandler\"q\n" +
	"\x0fRecievedMessage\x12\x1a\n" +
	"\bServerID\x18\x01 \x01(\tR\bServerID\x12$\n" +
	"\rAvailableSize\x18\x02 \x01(\tR\rAvailableSize\x12\x1c\n" +
	"\tchunkList\x18\x03 \x01(\tR\tchunkList2j\n" +
	"\x16MessageExchangeService\x12P\n" +
	"\x10MessageProcessor\x12\x1c.GRPCHandler.RecievedMessage\x1a\x1c.GRPCHandler.RecievedMessage\"\x00B\bZ\x06./GRPCb\x06proto3"

var (
	file_GRPC_TestProto_proto_rawDescOnce sync.Once
	file_GRPC_TestProto_proto_rawDescData []byte
)

func file_GRPC_TestProto_proto_rawDescGZIP() []byte {
	file_GRPC_TestProto_proto_rawDescOnce.Do(func() {
		file_GRPC_TestProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GRPC_TestProto_proto_rawDesc), len(file_GRPC_TestProto_proto_rawDesc)))
	})
	return file_GRPC_TestProto_proto_rawDescData
}

var file_GRPC_TestProto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GRPC_TestProto_proto_goTypes = []any{
	(*RecievedMessage)(nil), // 0: GRPCHandler.RecievedMessage
}
var file_GRPC_TestProto_proto_depIdxs = []int32{
	0, // 0: GRPCHandler.MessageExchangeService.MessageProcessor:input_type -> GRPCHandler.RecievedMessage
	0, // 1: GRPCHandler.MessageExchangeService.MessageProcessor:output_type -> GRPCHandler.RecievedMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GRPC_TestProto_proto_init() }
func file_GRPC_TestProto_proto_init() {
	if File_GRPC_TestProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GRPC_TestProto_proto_rawDesc), len(file_GRPC_TestProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GRPC_TestProto_proto_goTypes,
		DependencyIndexes: file_GRPC_TestProto_proto_depIdxs,
		MessageInfos:      file_GRPC_TestProto_proto_msgTypes,
	}.Build()
	File_GRPC_TestProto_proto = out.File
	file_GRPC_TestProto_proto_goTypes = nil
	file_GRPC_TestProto_proto_depIdxs = nil
}
